ARG SPARK_BASE=registry.cn-hangzhou.aliyuncs.com/imodel/livy-spark:0.8.0-incubating-spark_3.2.1_2.12-hadoop_3.2.0_cloud

FROM $SPARK_BASE

RUN cp alluxio-2.7.4-client.jar /opt/spark/jars/alluxio-2.7.4-client.jar